apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata:
  name: dev1-myserviceinterface_disable
  namespace: default
  labels:
    config.sdcio.dev/targetName: dev1
    config.sdcio.dev/targetNamespace: default
spec:
  priority: 20
  config:
    - path: /
      value:
        interface:
          - name: ethernet-1/5
            admin-state: disable
            mtu: 9100
