apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata:
  name: Config01
  namespace: default
  labels:
    config.sdcio.dev/targetName: dev1
    config.sdcio.dev/targetNamespace: default
spec:
  priority: 10
  config:
    - path: /
      value:
        interface:
          - name: ethernet-1/5
            description: Ethernet 1/5
            admin-state: enable
            mtu: 9100
            vlan-tagging: true
